### ISSUE TITLE
Relax version constraints on swift-collections

### ISSUE THREAD

**Issue by jpsim** [simba909/KVOSequence#6]
With swift-collections 1.1.0 now out (https://github.com/apple/swift-collections/releases/tag/1.1.0) it would be nice to relax the SwiftPM dependency constraints so that consumers of KVOSequence can also depend on the latest version of swift-collections.

I don't believe there are any breaking changes in swift-collections 1.1.0 that would impact this project, so this should be just a matter of updating `.upToNextMinor(from: "1.0.4")` to `from: "1.0.4"`.

Thanks!

**Comment by simba909** [comment]
This is a good suggestion! I'll get on it 👍🏻
